import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5175/login');
  await page.getByRole('button', { name: 'Subsystem Admin · Administrative Office admin@ems.ph / admin123 Use →' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Transactions' }).click();
  await page.getByRole('button', { name: 'New Transaction' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select a service…' }).click();
  await page.getByRole('option', { name: 'Medical Certificate — Sick' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Unassigned' }).click();
  await page.getByRole('option', { name: 'Ana Cruz' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Student' }).click();
  await page.getByLabel('Student').getByText('Student', { exact: true }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Cedrick');
  await page.getByRole('textbox', { name: 'Surname' }).click();
  await page.getByRole('textbox', { name: 'Surname' }).fill('Asusula');
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).click();
  await page.getByRole('textbox', { name: 'e.g., BSIT (BS Information' }).fill('BSIT');
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).click();
  await page.getByRole('textbox', { name: '09XXXXXXXXX' }).fill('09652365487');
  await page.getByRole('combobox').filter({ hasText: 'Select year level' }).click();
  await page.getByRole('option', { name: '3rd Year' }).click();
  await page.getByRole('textbox', { name: 'e.g., CommiT Society' }).click();
  await page.getByRole('textbox', { name: 'e.g., CommiT Society' }).fill('COMMITS');
  await page.locator('input[type="text"]').nth(1).click();
  await page.locator('input[type="text"]').nth(1).fill('Cough and High Fever');
  await page.getByPlaceholder('0', { exact: true }).click();
  await page.getByPlaceholder('0', { exact: true }).fill('7');
  await page.locator('input[type="text"]').nth(2).click();
  await page.locator('input[type="text"]').nth(2).fill('Certificated Issued ');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).press('ArrowLeft');
  await page.locator('input[type="text"]').nth(2).fill('Health Certificated Issued ');
  await page.getByRole('button', { name: 'Submit Transaction' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Mark as In Progress' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('.grid.grid-cols-1 > div:nth-child(2)').click();
  await page.getByRole('button', { name: 'Mark as Completed' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('link', { name: 'View' }).first().click();
  await page.getByRole('link', { name: 'Back to Transaction' }).click();
  await page.getByRole('button', { name: 'JM John Michael Garcia' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
});